= Script to generate the video near-rust-smart-contract-tutorial.mkv
Paulo Jerônimo, {localdate}
:icons: font
:idprefix:
:idseparator: -
:linkcss:
:nofooter:
:numbered:
:sectanchors:
:toc: left
:toc-title: {doctitle}

== Prerequisites

=== Use Ubuntu 22.04!

I did not have time to test this project in other environments yet.
So, please, use Ubuntu 22.04 to test this project.

If you have any problems running it, please open a GitHub issue and I
will try to help you!

=== Install the required softwares

==== ffmpeg

----
$ sudo apt install -y ffmpeg

$ ffmpeg -version | head -2
ffmpeg version 4.4.1-3ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-18ubuntu1)
----

==== yq

----
$ sudo snap install yq

$ yq --version
yq (https://github.com/mikefarah/yq/) version 4.24.2
----

=== Clone this repo and change your current directory to it

----
$ repo=https://github.com/paulojeronimo/near-rust-smart-contract-tutorial-video
$ git clone $repo && cd $(basename $repo)
----

Test your `yq` installation:

----
$ yq config.yaml

$ yq '.trim."01.1.mkv"' config.yaml
ss: '00:00:02'
to: '00:03:19'
----

References::
* https://mikefarah.gitbook.io/yq/

=== Download and extract the file media.tar.gz

Download the file `media.tar.gz` from this shared drive:
https://drive.google.com/drive/folders/1oeBzXnx_pv82RmlqywVq42Gaol0PlWwe

Move it to your cloned git repo directory and extract it:

----
$ tar xvfz media.tar.gz
----

The created directory structure should be this:

----
$ tree media
media
`-- simplescreenrecord
    |-- 01.1.mkv
    |-- 02.2.mkv
    |-- 03.3.mkv
    |-- 04.4-6.mkv
    |-- 05.7-10.mkv
    |-- 06.15.mkv
    |-- 07.mkv
    |-- 08.mkv
    |-- 09.mkv
    `-- 10.12-14.mkv

1 directory, 10 files
----

== Building

----
$ ./build.sh
----

== Author's functions

=== Generating the file media.tar.gz

----
$ ./build.sh media-tar-gz
----

=== Generating an HTML from README.adoc and publishing it in GitHub Pages

----
$ ./build.sh gh-pages
----
